"""
backend/graph_engine.py

Math Knowledge Graph – Traversal Engine
========================================

Responsibility
--------------
Execute graph traversal queries against the PostgreSQL knowledge graph stored
in Supabase.  All traversal logic is expressed as PostgreSQL Recursive CTEs so
the database engine handles the graph walk, keeping Python thin and stateless.

Architecture note
-----------------
Supabase's ``postgrest-py`` client exposes two low-level escape hatches:

1. ``supabase.rpc(fn_name, params)``   – calls a *PostgreSQL function* you
   define in your DB.  Great for reuse, but requires a migration per query.

2. ``supabase.postgrest``              – raw PostgREST; cannot run arbitrary SQL.

Because we want to ship without creating DB functions first, we use
``supabase.rpc`` by wrapping the CTE inside a PL/pgSQL function that is
lazily created in-process the first time the engine is imported.  A
``CREATE OR REPLACE FUNCTION`` call is made via the Supabase management client
(``psycopg2`` / ``asyncpg``).  In pure-Supabase projects without direct Postgres
access the recommended pattern is ``supabase.rpc`` with a pre-deployed function.

For maximum portability this module supports BOTH modes:
  - ``DIRECT_DB_URL`` env var set  →  raw psycopg2 (works in local dev & CI).
  - Only ``SUPABASE_*`` env vars   →  supabase-py rpc() (requires the helper
    function to be registered in the DB beforehand; see setup note below).

The public surface is intentionally small:

    get_prerequisite_chain(target_concept_code)  →  PrerequisiteChainResult
    get_immediate_prerequisite(target_concept_code, hard_only)  →  Node | None

Setup note (Supabase rpc path)
------------------------------
Run the content of ``backend/database/setup_rpc.sql`` once against your Supabase
project to register the required PostgreSQL helper functions.  That file is
generated by ``graph_engine.py`` itself; call ``python -m backend.graph_engine
--install`` to print it.
"""

from __future__ import annotations

import logging
import os
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from backend.models import Node, RelationshipType

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Response models (graph-engine–specific)
# ---------------------------------------------------------------------------


class PrerequisiteNode(BaseModel):
    """
    A single node as it appears in the prerequisite chain result.

    Carries an extra ``depth`` field indicating how many hops away from the
    originally queried concept this node sits (1 = immediate prerequisite,
    2 = grandparent, …).
    """

    model_config = ConfigDict(from_attributes=True)

    depth: int = Field(
        ...,
        ge=1,
        description=(
            "Traversal depth from the target concept. "
            "depth=1 → immediate prerequisite; depth=N → N hops away."
        ),
    )
    concept_code: str = Field(..., description="Stable curriculum identifier.")
    grade_level: int = Field(..., description="National curriculum grade (1–12).")
    topic_category: str = Field(..., description="Broad curriculum domain.")
    concept_name_vn: str = Field(..., description="Vietnamese name of the concept.")
    concept_description: Optional[str] = Field(
        None, description="Full description of the concept."
    )
    mastery_question: Optional[str] = Field(
        None, description="Diagnostic question that validates mastery."
    )


class PrerequisiteChainResult(BaseModel):
    """
    Structured response returned by ``get_prerequisite_chain``.

    ``chain`` is ordered from the *shallowest* (depth=1, immediate prerequisite)
    to the *deepest* (foundational root node), matching the natural remediation
    order an adaptive engine would present to a student.
    """

    target_concept_code: str = Field(
        ..., description="The concept code that was queried."
    )
    total_prerequisites: int = Field(
        ..., ge=0, description="Total number of prerequisite nodes discovered."
    )
    chain: List[PrerequisiteNode] = Field(
        default_factory=list,
        description=(
            "Ordered prerequisite chain, shallowest (depth=1) to deepest root."
        ),
    )


# ---------------------------------------------------------------------------
# SQL for the Recursive CTE
# ---------------------------------------------------------------------------

# This query is parameterised by a single named placeholder ``%(concept_code)s``
# (psycopg2 style).  When called via Supabase rpc, parameters are passed as a
# JSON object ``{"p_concept_code": "..."}`` to the helper function below.
#
# Traversal logic:
#   1. Anchor: find the target node by concept_code.
#   2. Recursive step: walk edges backwards (edge.target → edge.source) to
#      collect all ancestors, accumulating the traversal depth.
#   3. Final SELECT: join the accumulated node IDs back to the nodes table to
#      return full node details, ordered by depth ascending.
#
# The CTE correctly handles:
#   - DAGs (directed acyclic graphs) with multiple paths to the same root.
#   - Cycles: ``UNION`` (not ``UNION ALL``) in the recursive term deduplicates
#     already-visited node IDs, so the query terminates even if the graph has
#     an accidental cycle.
_RECURSIVE_CTE_SQL = """
WITH RECURSIVE

  -- Step 1: Resolve the target concept_code to its UUID and use it as the
  --         starting point for the backwards traversal.
  target AS (
      SELECT id AS node_id
      FROM   nodes
      WHERE  concept_code = %(concept_code)s
      LIMIT  1
  ),

  -- Step 2: Recursive traversal.
  --   Each iteration adds the *source* nodes of edges whose *target* matches
  --   nodes already in the working set.  This walks the graph "backwards",
  --   i.e., from dependent → prerequisite → prerequisite-of-prerequisite …
  prerequisite_tree AS (

      -- Anchor member: the immediate prerequisites (depth 1).
      SELECT
          e.source_node_id  AS node_id,
          1                 AS depth
      FROM  edges e
      JOIN  target t ON e.target_node_id = t.node_id

      UNION  -- UNION (not UNION ALL) to deduplicate already-visited nodes.

      -- Recursive member: prerequisites of prerequisites.
      SELECT
          e.source_node_id       AS node_id,
          pt.depth + 1           AS depth
      FROM  edges e
      JOIN  prerequisite_tree pt ON e.target_node_id = pt.node_id
  )

-- Step 3: Join back to the nodes table to get full node metadata.
--         When the same node is reachable via multiple paths (diamond DAG),
--         MIN(depth) picks the shortest path depth, which is the most useful
--         value for display ordering.
SELECT
    MIN(pt.depth)            AS depth,
    n.concept_code,
    n.grade_level,
    n.topic_category,
    n.concept_name_vn,
    n.concept_description,
    n.mastery_question
FROM  prerequisite_tree pt
JOIN  nodes n ON n.id = pt.node_id
GROUP BY
    n.concept_code,
    n.grade_level,
    n.topic_category,
    n.concept_name_vn,
    n.concept_description,
    n.mastery_question
ORDER BY
    depth ASC,          -- Shallower prerequisites first (depth=1 = immediate).
    n.grade_level ASC;  -- Within the same depth, lower grade first.
"""

# Lighter query for the webhook endpoint: returns only the concept_code and
# mastery_question of the *single* immediate HARD prerequisite, if any.
_IMMEDIATE_HARD_PREREQ_SQL = """
SELECT
    n.concept_code,
    n.grade_level,
    n.topic_category,
    n.concept_name_vn,
    n.concept_description,
    n.mastery_question,
    n.id,
    n.created_at
FROM  edges e
JOIN  nodes target_n ON target_n.id     = e.target_node_id
JOIN  nodes n        ON n.id            = e.source_node_id
WHERE target_n.concept_code = %(concept_code)s
  AND e.relationship_type   = 'HARD_PREREQUISITE'
ORDER BY n.grade_level DESC  -- Closest hard prerequisite by grade proximity.
LIMIT 1;
"""


# ---------------------------------------------------------------------------
# Database connection helpers
# ---------------------------------------------------------------------------

def _get_psycopg2_connection():
    """
    Return a live psycopg2 connection using ``DIRECT_DB_URL`` from the
    environment.  Raises ``RuntimeError`` if the variable is absent.

    The caller is responsible for closing the connection (use as a context
    manager or call ``.close()`` explicitly).
    """
    try:
        import psycopg2  # type: ignore
        import psycopg2.extras  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "psycopg2 is not installed.  Run: pip install psycopg2-binary"
        ) from exc

    db_url = os.environ.get("DIRECT_DB_URL")
    if not db_url:
        raise RuntimeError(
            "DIRECT_DB_URL environment variable is not set. "
            "Set it to your Supabase PostgreSQL connection string, e.g.: "
            "postgresql://postgres:<password>@db.<project>.supabase.co:5432/postgres"
        )
    return psycopg2.connect(db_url, cursor_factory=psycopg2.extras.RealDictCursor)


def _get_supabase_client():
    """
    Return a configured ``supabase-py`` client using SUPABASE_URL and
    SUPABASE_SERVICE_ROLE_KEY from the environment.

    We use the *service role* key (not the anon key) so that the backend can
    bypass Row-Level-Security and read all data.
    """
    try:
        from supabase import create_client, Client  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "supabase-py is not installed.  Run: pip install supabase"
        ) from exc

    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key:
        raise RuntimeError(
            "SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must both be set "
            "in the environment."
        )
    return create_client(url, key)


# ---------------------------------------------------------------------------
# Internal execution helpers
# ---------------------------------------------------------------------------

def _execute_cte_direct(sql: str, params: dict) -> List[dict]:
    """
    Execute a parameterised SQL query via a direct psycopg2 connection and
    return all rows as a list of plain dicts.

    Parameters
    ----------
    sql:    The SQL string with ``%(name)s`` placeholders.
    params: Dict mapping placeholder names to values.

    Returns
    -------
    List of row dicts; empty list if no rows matched.
    """
    conn = _get_psycopg2_connection()
    try:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            rows = cur.fetchall()
            # psycopg2 RealDictCursor returns RealDictRow objects; cast to plain
            # dict so Pydantic model_validate() doesn't need psycopg2 installed.
            return [dict(row) for row in rows]
    finally:
        conn.close()


def _execute_cte_via_rpc(rpc_function: str, params: dict) -> List[dict]:
    """
    Execute a graph traversal by calling a pre-registered PostgreSQL function
    via Supabase rpc().

    The PostgreSQL function must be created in your Supabase project before
    this path is used.  See ``backend/database/setup_rpc.sql`` for the DDL.

    Parameters
    ----------
    rpc_function: Name of the PostgreSQL function to call.
    params:       Dict of named parameters passed as the JSON argument to rpc().

    Returns
    -------
    List of row dicts returned by the function.
    """
    client = _get_supabase_client()
    response = client.rpc(rpc_function, params).execute()
    # supabase-py >= 2.x raises on HTTP errors; `.data` holds the result list.
    return response.data or []


def _execute_sqlite_direct(sql: str, params: dict) -> List[dict]:
    """Execute SQL via local SQLite DB when Supabase config is absent."""
    import sqlite3
    db_path = os.environ.get("SQLITE_DB_PATH", "math_graph.db")
    if not os.path.exists(db_path):
        raise RuntimeError(f"SQLite database not found at {db_path}")
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    try:
        # Convert psycopg2 placeholder style %(param)s to SQLite style :param
        for k in params.keys():
            sql = sql.replace(f"%({k})s", f":{k}")
            
        cur = conn.cursor()
        cur.execute(sql, params)
        rows = cur.fetchall()
        return [dict(row) for row in rows]
    finally:
        conn.close()


def _run_query(sql: str, params: dict, rpc_fallback: str) -> List[dict]:
    """
    Dispatch a graph query to the correct backend.

    Priority:
      1. ``DIRECT_DB_URL`` is set  →  raw psycopg2.
      2. ``SUPABASE_URL`` is set   →  supabase-py rpc().
      3. Fallback                  →  local SQLite DB.
    """
    if os.environ.get("DIRECT_DB_URL"):
        logger.debug("Graph engine: using direct psycopg2 connection.")
        return _execute_cte_direct(sql, params)
    elif os.environ.get("SUPABASE_URL"):
        logger.debug("Graph engine: using Supabase rpc() → %s.", rpc_fallback)
        rpc_params = {f"p_{k}": v for k, v in params.items()}
        return _execute_cte_rpc(rpc_fallback, rpc_params)
    else:
        logger.debug("Graph engine: using local SQLite connection.")
        return _execute_sqlite_direct(sql, params)


# Alias to avoid shadowing the public name used below.
_execute_cte_rpc = _execute_cte_via_rpc


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def get_prerequisite_chain(target_concept_code: str) -> PrerequisiteChainResult:
    """
    Return the full prerequisite chain for a given concept, traversing from
    the immediate prerequisites all the way down to the foundational root nodes.

    Traversal is performed by a single PostgreSQL Recursive CTE, so the entire
    graph walk happens inside the database with no round-trips per hop.

    Parameters
    ----------
    target_concept_code:
        The ``concept_code`` of the concept whose prerequisites we want.
        Example: ``"G9_ALG_QUAD_EQ"`` (Quadratic Equations, Grade 9).

    Returns
    -------
    PrerequisiteChainResult
        ``.chain`` is ordered shallowest → deepest (remediation order).
        ``.total_prerequisites`` is the count of unique ancestors found.
        If the concept has no prerequisites, ``.chain`` is an empty list.

    Raises
    ------
    ValueError
        If ``target_concept_code`` is empty or blank.
    LookupError
        If the concept_code does not exist in the ``nodes`` table.
    RuntimeError
        On database connectivity or configuration failures.
    """
    # --- Input sanitisation --------------------------------------------------
    concept_code = target_concept_code.strip().upper()
    if not concept_code:
        raise ValueError("target_concept_code must be a non-empty string.")

    logger.info("Graph traversal requested for concept_code='%s'.", concept_code)

    # --- Verify the target node exists (fast single-row lookup) --------------
    # We do this before the expensive CTE so we can return a clean LookupError
    # rather than an empty list that could be misread as "no prerequisites".
    _verify_node_exists(concept_code)

    # --- Execute the Recursive CTE -------------------------------------------
    try:
        rows = _run_query(
            sql=_RECURSIVE_CTE_SQL,
            params={"concept_code": concept_code},
            rpc_fallback="get_prerequisite_chain",  # matches setup_rpc.sql
        )
    except Exception as exc:
        logger.exception(
            "Database error during prerequisite traversal for '%s'.", concept_code
        )
        raise RuntimeError(
            f"Failed to execute prerequisite traversal for '{concept_code}': {exc}"
        ) from exc

    # --- Parse rows into typed models ----------------------------------------
    chain: List[PrerequisiteNode] = []
    for row in rows:
        try:
            chain.append(PrerequisiteNode.model_validate(row))
        except Exception as parse_err:
            # Log malformed rows but don't abort the entire response.
            logger.warning(
                "Could not parse prerequisite row for '%s': %s | row=%s",
                concept_code,
                parse_err,
                row,
            )

    logger.info(
        "Prerequisite chain for '%s': %d nodes found (deepest depth=%d).",
        concept_code,
        len(chain),
        chain[-1].depth if chain else 0,
    )

    return PrerequisiteChainResult(
        target_concept_code=concept_code,
        total_prerequisites=len(chain),
        chain=chain,
    )


def get_immediate_prerequisite(
    target_concept_code: str,
    hard_only: bool = True,
) -> Optional[Node]:
    """
    Return the *single* most relevant immediate prerequisite for the given
    concept, or ``None`` if none exists.

    This is the hot path for the AI grading webhook: when a student fails a
    concept, the webhook calls this function to surface the exact mastery
    question the student needs to answer next.

    Parameters
    ----------
    target_concept_code:
        The concept_code of the *failed* concept.
    hard_only:
        If ``True`` (default), only HARD_PREREQUISITEs are considered.
        Set to ``False`` to also include SOFT_PREREQUISITEs.

    Returns
    -------
    ``Node`` for the most proximate prerequisite, or ``None`` if not found.

    Raises
    ------
    LookupError
        If the concept_code does not exist in the ``nodes`` table.
    RuntimeError
        On database connectivity or configuration failures.
    """
    concept_code = target_concept_code.strip().upper()
    if not concept_code:
        raise ValueError("target_concept_code must be a non-empty string.")

    # Verify the concept exists before we run a more expensive query.
    _verify_node_exists(concept_code)

    # Build SQL dynamically based on hard_only flag.
    rel_filter = (
        "AND e.relationship_type = 'HARD_PREREQUISITE'"
        if hard_only
        else ""
    )
    sql = f"""
        SELECT
            n.id,
            n.concept_code,
            n.grade_level,
            n.topic_category,
            n.concept_name_vn,
            n.concept_description,
            n.mastery_question,
            n.created_at
        FROM  edges e
        JOIN  nodes target_n ON target_n.id  = e.target_node_id
        JOIN  nodes n        ON n.id         = e.source_node_id
        WHERE target_n.concept_code = %(concept_code)s
          {rel_filter}
        ORDER BY n.grade_level DESC
        LIMIT 1;
    """

    try:
        rows = _run_query(
            sql=sql,
            params={"concept_code": concept_code},
            rpc_fallback="get_immediate_prerequisite",
        )
    except Exception as exc:
        logger.exception(
            "Database error fetching immediate prerequisite for '%s'.", concept_code
        )
        raise RuntimeError(
            f"Failed to fetch immediate prerequisite for '{concept_code}': {exc}"
        ) from exc

    if not rows:
        logger.info(
            "No immediate prerequisite found for '%s' (hard_only=%s).",
            concept_code,
            hard_only,
        )
        return None

    return Node.model_validate(rows[0])


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _verify_node_exists(concept_code: str) -> None:
    """
    Raise ``LookupError`` if the given concept_code is not present in the DB.

    This is a lightweight existence check (SELECT 1 LIMIT 1) to give callers
    a clean LookupError instead of an empty/ambiguous result set.

    Parameters
    ----------
    concept_code: Already-normalised (stripped, uppercased) concept code.

    Raises
    ------
    LookupError: If no node with this concept_code exists.
    RuntimeError: On database failure.
    """
    existence_sql = """
        SELECT 1 AS node_exists
        FROM   nodes
        WHERE  concept_code = %(concept_code)s
        LIMIT  1;
    """

    if os.environ.get("DIRECT_DB_URL"):
        rows = _execute_cte_direct(existence_sql, {"concept_code": concept_code})
    elif os.environ.get("SUPABASE_URL"):
        # Via supabase-py PostgREST (no raw SQL needed for a simple equality filter).
        client = _get_supabase_client()
        resp = (
            client.table("nodes")
            .select("concept_code")
            .eq("concept_code", concept_code)
            .limit(1)
            .execute()
        )
        rows = resp.data or []
    else:
        # SQLite fallback
        rows = _execute_sqlite_direct(existence_sql, {"concept_code": concept_code})

    if not rows:
        raise LookupError(
            f"Concept code '{concept_code}' was not found in the nodes table. "
            "Verify the code is correct and has been seeded into the database."
        )
